config.load_autoconfig()

config.set('colors.webpage.bg', colorBg)

config.set('colors.completion.even.bg', colorBg)
config.set('colors.completion.odd.bg', colorBg)
config.set('colors.completion.fg', colorFg)
config.set('colors.completion.item.selected.bg', color1)
config.set('colors.completion.item.selected.border.bottom', color1)
config.set('colors.completion.item.selected.border.top', color1)
config.set('colors.completion.item.selected.fg', colorFg)
config.set('colors.completion.item.selected.match.fg', colorFg)

config.set('colors.completion.item.selected.fg', color2)
config.set('colors.completion.item.selected.match.fg', color3)
config.set('colors.completion.match.fg', color3)

config.set('colors.completion.scrollbar.bg', colorBg)
config.set('colors.completion.scrollbar.fg', color1)

config.set('colors.tabs.bar.bg', colorBg)
config.set('colors.tabs.even.bg', colorBg)
config.set('colors.tabs.even.fg', colorFg)
config.set('colors.tabs.odd.bg', colorBg)
config.set('colors.tabs.odd.fg', colorFg)
config.set('colors.tabs.pinned.even.bg', colorBg)
config.set('colors.tabs.pinned.even.fg', colorFg)
config.set('colors.tabs.pinned.odd.bg', colorBg)
config.set('colors.tabs.pinned.odd.fg', colorFg)
config.set('colors.tabs.pinned.selected.even.bg', color1)
config.set('colors.tabs.pinned.selected.even.fg', colorFg)
config.set('colors.tabs.pinned.selected.odd.bg', color1)
config.set('colors.tabs.pinned.selected.odd.fg', colorFg)
config.set('colors.tabs.selected.even.bg', color1)
config.set('colors.tabs.selected.even.fg', colorFg)
config.set('colors.tabs.selected.odd.bg', color1)
config.set('colors.tabs.selected.odd.fg', colorFg)

config.set('colors.downloads.bar.bg', colorBg)
config.set('colors.downloads.error.bg', color2)
config.set('colors.downloads.error.fg', colorFg)
config.set('colors.downloads.start.bg', colorBg)
config.set('colors.downloads.start.fg', colorFg)
config.set('colors.downloads.stop.bg', color4)
config.set('colors.downloads.stop.fg', colorBg)

config.set('hints.border', '1px solid ' + color1)
config.set('colors.hints.bg', colorFg)
config.set('colors.hints.fg', colorBg)
config.set('colors.hints.match.fg', colorFg)

config.set('colors.statusbar.caret.bg', colorBg)
config.set('colors.statusbar.caret.fg', colorFg)
config.set('colors.statusbar.caret.selection.bg', color2)
config.set('colors.statusbar.caret.selection.fg', color1)
config.set('colors.statusbar.command.bg', colorBg)
config.set('colors.statusbar.command.fg', colorFg)
config.set('colors.statusbar.insert.bg', color3)
config.set('colors.statusbar.insert.fg', colorBg)
config.set('colors.statusbar.normal.bg', colorBg)
config.set('colors.statusbar.normal.fg', colorFg)
config.set('colors.statusbar.passthrough.bg', color2)
config.set('colors.statusbar.passthrough.fg', colorBg)
config.set('colors.statusbar.progress.bg', color3)
config.set('colors.statusbar.private.bg', color3)
config.set('colors.statusbar.private.fg', colorBg)
config.set('colors.statusbar.url.hover.fg', colorFg)
config.set('colors.statusbar.url.success.http.fg', colorFg)
config.set('colors.statusbar.url.success.https.fg', color5)
config.set('colors.statusbar.url.warn.fg', color2)

f = str(fontSize) + "pt " + font
config.set('fonts.completion.category', f)
config.set('fonts.completion.entry', f)
config.set('fonts.debug_console', f)
config.set('fonts.downloads', f)
config.set('fonts.hints', f)
config.set('fonts.keyhint', f)
config.set('fonts.messages.error', f)
config.set('fonts.messages.info', f)
config.set('fonts.messages.warning', f)
config.set('fonts.monospace', f)
config.set('fonts.prompts', f)
config.set('fonts.statusbar', f)
config.set('fonts.tabs', f)
