config.load_autoconfig()
colorAccent = color5
colorAccent2 = color4
colorAccentDark = color13
colorWarn = color3
colorBad = color2
colorGood = color4

config.set('colors.webpage.bg', colorBg)

config.set('colors.completion.even.bg', colorBg)
config.set('colors.completion.odd.bg', colorBg)
config.set('colors.completion.fg', colorFg)
config.set('colors.completion.item.selected.bg', colorAccent)
config.set('colors.completion.item.selected.border.bottom', colorAccent)
config.set('colors.completion.item.selected.border.top', colorAccent)
config.set('colors.completion.item.selected.fg', colorFg)
config.set('colors.completion.item.selected.match.fg', colorAccent2)
config.set('colors.completion.match.fg', colorAccent2)

config.set('colors.completion.scrollbar.bg', colorBg)
config.set('colors.completion.scrollbar.fg', colorAccent)

config.set('colors.tabs.bar.bg', colorBg)
config.set('colors.tabs.even.bg', colorBg)
config.set('colors.tabs.even.fg', colorFg)
config.set('colors.tabs.odd.bg', colorBg)
config.set('colors.tabs.odd.fg', colorFg)
config.set('colors.tabs.pinned.even.bg', colorBg)
config.set('colors.tabs.pinned.even.fg', colorFg)
config.set('colors.tabs.pinned.odd.bg', colorBg)
config.set('colors.tabs.pinned.odd.fg', colorFg)
config.set('colors.tabs.pinned.selected.even.bg', colorAccent)
config.set('colors.tabs.pinned.selected.even.fg', colorFg)
config.set('colors.tabs.pinned.selected.odd.bg', colorAccent)
config.set('colors.tabs.pinned.selected.odd.fg', colorFg)
config.set('colors.tabs.selected.even.bg', colorAccentDark)
config.set('colors.tabs.selected.even.fg', colorFg)
config.set('colors.tabs.selected.odd.bg', colorAccentDark)
config.set('colors.tabs.selected.odd.fg', colorFg)

config.set('colors.downloads.bar.bg', colorBg)
config.set('colors.downloads.error.bg', colorBad)
config.set('colors.downloads.error.fg', colorFg)
config.set('colors.downloads.start.bg', colorBg)
config.set('colors.downloads.start.fg', colorFg)
config.set('colors.downloads.stop.bg', colorGood)
config.set('colors.downloads.stop.fg', colorBg)

config.set('hints.border', '1px solid ' + colorAccent)
config.set('colors.hints.bg', colorAccentDark)
config.set('colors.hints.fg', colorFg)
config.set('colors.hints.match.fg', colorFg)

config.set('colors.statusbar.caret.bg', colorBg)
config.set('colors.statusbar.caret.fg', colorFg)
config.set('colors.statusbar.caret.selection.bg', colorWarn)
config.set('colors.statusbar.caret.selection.fg', colorAccent)
config.set('colors.statusbar.command.bg', colorBg)
config.set('colors.statusbar.command.fg', colorFg)
config.set('colors.statusbar.insert.bg', colorGood)
config.set('colors.statusbar.insert.fg', colorBg)
config.set('colors.statusbar.normal.bg', colorBg)
config.set('colors.statusbar.normal.fg', colorFg)
config.set('colors.statusbar.passthrough.bg', colorBad)
config.set('colors.statusbar.passthrough.fg', colorBg)
config.set('colors.statusbar.progress.bg', colorAccent)
config.set('colors.statusbar.private.bg', colorAccent)
config.set('colors.statusbar.private.fg', colorBg)
config.set('colors.statusbar.url.hover.fg', colorFg)
config.set('colors.statusbar.url.success.http.fg', colorFg)
config.set('colors.statusbar.url.success.https.fg', colorGood)
config.set('colors.statusbar.url.warn.fg', colorBad)

f = str(fontSize) + "pt " + font
config.set('fonts.completion.category', f)
config.set('fonts.completion.entry', f)
config.set('fonts.debug_console', f)
config.set('fonts.downloads', f)
config.set('fonts.hints', f)
config.set('fonts.keyhint', f)
config.set('fonts.messages.error', f)
config.set('fonts.messages.info', f)
config.set('fonts.messages.warning', f)
config.set('fonts.prompts', f)
config.set('fonts.statusbar', f)
config.set('fonts.tabs', f)
